version: 3.0

# 配置解释见 https://docs.xray.cool/#/configration/plugins
plugins:
  max_parallel: 30
  xss:
    enabled: true
    ie_feature: false
    include_cookie: false
  baseline:
    enabled: false
    detect_outdated_ssl_version: false
    detect_cors_header_config: true
    detect_server_error_page: true
    detect_serialization_data_in_params: true
    detect_cookie_password_leak: true
    detect_http_header_config: false
    detect_unsafe_scheme: false
    detect_cookie_httponly: false
    detect_china_id_card_number: false
    detect_china_phone_number: false
    detect_china_bank_card: false
    detect_china_address: false
  cmd_injection:
    enabled: true
    detect_blind_injection: false
    # 检测非注入型场景，比如参数是一个完整的命令
    detect_none_injection_case: false
  crlf_injection:
    enabled: true
  dirscan:
    enabled: false
    depth: 1
    dictionary: ""
  jsonp:
    enabled: true
  path_traversal:
    enabled: true
  redirect:
    enabled: true
  sqldet:
    enabled: true
    error_based_detection: true
    boolean_based_detection: true
    time_based_detection: true
    # 下面两个选项很危险，开启之后可以增加检测率，但是有破坏数据库数据的可能性，请务必了解工作原理之后再开启
    dangerously_use_comment_in_sql: false
    dangerously_use_or_in_sql: false
  ssrf:
    enabled: true
  xxe:
    enabled: true
  upload:
    enabled: true
  brute_force:
    enabled: false
    detect_default_password: true
    detect_unsafe_login_method: false
    username_dictionary: ""
    password_dictionary: ""
  phantasm:
    enabled: true
    depth: 1
    poc:
      - poc-yaml-activemq-cve-2016-3088
      - poc-yaml-apache-flink-upload-rce
      - poc-yaml-citrix-cve-2019-19781-path-traversal
      - poc-yaml-citrix-cve-2020-8191-xss
      - poc-yaml-citrix-cve-2020-8193-unauthorized
      - poc-yaml-elasticsearch-cve-2015-1427
      - poc-yaml-elasticsearch-cve-2015-3337-lfi
      - poc-yaml-solr-cve-2017-12629-xxe
      - poc-yaml-solr-cve-2019-0193
      - poc-yaml-solr-velocity-template-rce
      - poc-yaml-spark-unauth
      - poc-yaml-spring-cloud-cve-2020-5405
      - poc-yaml-spring-cloud-cve-2020-5410
      - poc-yaml-spring-cve-2016-4977
      - poc-yaml-springcloud-cve-2019-3799
      - poc-yaml-supervisord-cve-2017-11610
      - poc-yaml-tomcat-cve-2018-11759
      - poc-yaml-weblogic-cve-2017-10271-reverse
      - poc-yaml-weblogic-cve-2019-2729-1
      - poc-yaml-weblogic-cve-2019-2729-2
      - poc-yaml-weblogic-ssrf
      - poc-yaml-weblogic-cve-2017-10271
      - poc-yaml-weblogic-cve-2019-2725
      - poc-yaml-zabbix-authentication-bypass
      - poc-yaml-zabbix-cve-2016-10134-sqli
      - poc-go-php-cve-2019-11043-rce
      - poc-go-tomcat-cve-2020-1938
      - poc-go-tomcat-put

log:
  level: info # 支持 debug, info, warn, error, fatal

# 配置解释见 https://docs.xray.cool/#/configration/mitm
mitm:
  ca_cert: ./ca.crt
  ca_key: ./ca.key
  auth:
    username: ""
    password: ""
  restriction:
    includes: # 允许扫描的域，此处无协议
    - '*' # 表示允许所有的域名和 path
    - 'example.com' # 表示允许 example.com 下的所有 path
    - "example.com/admin*" # 表示允许 example.com 下的 /admin 开头的 path
    excludes:
    - '*google*'
    - '*github*'
    - '*.gov.cn'
    - '*.edu.cn'
    - '*chaitin*'
    - '*xray.cool'
  allow_ip_range: []
  queue:
    max_length: 3000
  proxy_header:
    via: "" # 如果不为空，proxy 将添加类似 Via: 1.1 $some-value-$random 的 http 头
    x_forwarded: false # 是否添加 X-Forwarded-{For,Host,Proto,Url} 四个 http 头
  upstream_proxy: "" # mitm 的全部流量继续使用 proxy

# 配置解释见 https://docs.xray.cool/#/configration/basic-crawler
basic_crawler:
  max_depth: 0 # 爬虫最大深度, 0 为无限制
  max_count_of_links: 0 # 本次扫描总共爬取的最大连接数， 0 为无限制
  allow_visit_parent_path: false # 是否允许访问父目录, 如果扫描目标为 example.com/a/， 如果该项为 false, 那么就不会爬取 example.com/ 这级目录的内容
  restriction: # 和 mitm 中的写法一致, 有个点需要注意的是如果当前目标为 example.com 那么会自动添加 example.com 到 includes 中。
    includes: []
    excludes:
    - '*google*'

# 配置解释见 https://docs.xray.cool/#/configration/reverse
# 默认配置无法检测依赖反连平台的漏洞，这些漏洞包括 fastjson，ssrf，shiro 等
# 新版将 RMI 服务于 HTTP 服务进行了融合，所以配置项进行了删减，但 RMI 的端口复用不适用于 nginx 反代的情况，这种情况需要手动添加 RMI 的配置，见上述文档中的说明
reverse:
  db_file_path: ""
  token: ""
  http:
    enabled: true
    listen_ip: 127.0.0.1
    listen_port: ""
    # 在哪个 http header 中取 ip，为空代表从 REMOTE_ADDR 中取
    ip_header: ""
  dns:
    enabled: false
    listen_ip: 127.0.0.1
    domain: ""
    is_domain_name_server: false
    # 静态解析规则
    resolve:
    - type: A # A, AAAA, TXT 三种
      record: localhost
      value: 127.0.0.1
      ttl: 60
  client:
    http_base_url: ""
    dns_server_ip: ""
    remote_server: false

# 配置解释见 https://docs.xray.cool/#/configration/http
http:
  proxy: "" # 漏洞扫描时使用的代理，如需设置多个代理，请见文档相关说明
  dial_timeout: 5 # 建立 tcp 连接的超时时间
  read_timeout: 10 # 读取 http 响应的超时时间，不可太小，否则会影响到 sql 时间盲注的判断
  fail_retries: 1 # 请求失败的重试次数，0 则不重试
  max_redirect: 5 # 单个请求最大允许的跳转数
  max_qps: 500 # 每秒最大请求数
  max_conns_per_host: 80 # 同一 host 最大允许的连接数，可以根据目标主机性能适当增大。
  max_resp_body_size: 8388608 # 8M，单个请求最大允许的响应体大小，超过该值 body 就会被截断
  headers: # 每个请求预置的 http 头
    User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0
    # Cookie: key=value
  allow_methods: # 允许使用 http 方法
    - HEAD
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
    - CONNECT
    - PROPFIND
    - MOVE
  tls_skip_verify: true # 是否验证目标网站的 https 证书。
  enable_http2: false # 是否启用 http2
